---
version: "2.1"
services:
  localstack:
    image: localstack/localstack@sha256:7a74c805a2c4173553c4fb67b03b7ce2015062491d8317a107b8e58d6c93dc58
    network_mode: bridge
    environment:
      SERVICES: sns,s3,sqs
      DEBUG: 0
    ports:
      - 4566:4566
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
