---
version: "2.1"
services:
  localstack:
    image: localstack/localstack@sha256:b1b9f264d6c63fcacc7009a0924fd444f20d2149e9874500683d6c37e980dd60
    network_mode: bridge
    environment:
      SERVICES: sns,s3,sqs
      DEBUG: 0
    ports:
      - 4566:4566
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
