---
version: "2.1"
services:
  localstack:
    image: localstack/localstack@sha256:996c61b13801f9a0f539550ce5364b821c95e1bfb691b37a329d0ef4f2dcc362
    network_mode: bridge
    environment:
      SERVICES: sns,s3,sqs
      DEBUG: 0
    ports:
      - 4566:4566
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
