name: Release latest code for production deploy
permissions: {}
on:
  release:
    types: [published]

jobs:
  run:
    name: Run local action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false
      - name: Run latest-tag
        uses: EndBug/latest-tag@7589411ebda7bc8f98deb2dbc37e3dc45828f7d0 # v1.6.2
        with:
          ref: production
          force-branch: true
