name: Release latest code for production deploy
permissions: {}
on:
  release:
    types: [published]

jobs:
  run:
    name: Run local action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@master
        with:
          persist-credentials: false
      - name: Run latest-tag
        uses: EndBug/latest-tag@latest
        with:
          tag-name: production
          force-branch: true
